version: 0.2

phases:
  pre_build:
    commands:
      - rm -rf node_modules/
      - rm -rf package-lock.json
  install:
    command:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
